(ns snowbird.analysis.custom-rules.apex-filename-must-match-pattern)

(def files
  [ "/Users/rgscherf/projects/tech-debt-measurement/classes/Class_ServiceLayerUtil_Test.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/Batch_UpdateContacts_Test.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/ChangePasswordController.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/AssetTrigger_Test.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/Model_Asset.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/Scheduled_Batch_GISAddressUpdateClass.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/Model_OrderItem_Test.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/Class_OutcomeException.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/AccountContactTrigger_Test.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/telusComWsdlRmoOrdermgmtEquipmentre.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/TestFactory_Knock.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/Model_WorkflowTemplate_Test.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/LtgController_CSDClaim.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/TriggerHandler_SMS_Test.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/LtgController_OutcomeLiteTest.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/xmlschemaTmiTelusComXsdEnterpriseB.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/CreateCaseFromEmail.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/Batch_RecordsDeleteClass_Test.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/Controller_GeopointeCreateLead.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/Model_Task_Test.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/Model_GenericEventMetadata.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/CommunitiesLoginController.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/RetrieveNextUtils_Test.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/Model_BillingData.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/Controller_DPOBulkUpdate_Test.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/Batch_UpdateContactwithAccountId.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/Controller_DropAccountMemberRole_Test.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/Batch_DeleteOldBillingData_Test.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/Class_RemoveOrphanCustomerAddress_Test.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/MyProfilePageController.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/Class_OutcomeContactUtil.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/Class_SMS_JSON.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/Controller_ContactWorkOrderDisplay.cls"
   "/Users/rgscherf/projects/tech-debt-measurement/classes/Controller_MyProfilePage.cls"])

